### ISSUE TITLE
frequency normalisation is not efficient

### ISSUE THREAD

**Issue by zaccharieramzi** [CEA-COSMIC/pysap-mri#10]
[The frequency normalisation](https://github.com/CEA-COSMIC/pysap-mri/blob/master/mri/reconstruct/utils.py#L78-L105) in the case of non-uniform FFT is, I think, wrong. Indeed, it doesn't output frequency locations between `-0.5` and `0.5`, but between `0` and `0.5`. This is because we divide by `2*max` instead of dividing by `max` and then substracting `0.5`.

We should rewrite it to make sure it does the correct stuff and have a unit test for it.

We should also allow `float` for `Kmax`. Right now it is said to be the only case in the docs, but actually it is not. Only an array-like is allowed (see [this call](https://github.com/CEA-COSMIC/pysap-mri/blob/master/mri/reconstruct/utils.py#L101)).

**Comment by philouc** [comment]
you're right. Normally, the normalized freq ranges between -0.5 (excluded) and 0.5 (included). GO ahead!

**Comment by LElgueddari** [comment]
There is two different things here, we are only talking about normalization, hence if a user gives a sample equal to 0 you may not want to change this point because it corresponds exactly to the 0 frequency.
The second point comes from the Kmax: [Kmax](http://mriquestions.com/field-of-view-fov.html) has a physical definition. so if you take into account those two facts the definition is correct. 
By the way 0, 0.5 is included in -0.5, 0.5

**Comment by LElgueddari** [comment]
You can see this function as going from the frequency f in Hz to a digital frequency f_d with f_e = f/f_s, with f_s being the sampling frequency. If Nyquist is satisfied than f_s should be exactly twice the maximal frequency (i.e. Kmax)

**Comment by zaccharieramzi** [comment]
Ok so one thing I was missing is that the samples we normalize have an actual physical meaning indeed.

Since they should be centered around 0 (more or less) if we want to span the whole frequency space, dividing by `2*Kmax` is enough to normalize it between `[-0.5; 0.5[`.

We could still modify the function slightly to be more efficient (i.e. get rid of the for loops) and accept a float as input for `Kmax`.

**Comment by chaithyagr** [comment]
@zaccharieramzi , I had a discussion with @LElgueddari for this. I think this is a stale issue at this point. Can you please help me understand why is it that current implementation is not efficient?

> We could still modify the function slightly to be more efficient (i.e. get rid of the for loops) and accept a float as input for Kmax.

I am assuming you are referring this for loop. We need this for loop to iterate over dimension.
https://github.com/CEA-COSMIC/pysap-mri/blob/08efd564606f7ef3bb16e1eff1fcddadd36d1e8c/mri/reconstruct/utils.py#L97-L101


The only improvements that I can think of is, something sort of:
```python
    if Kmax is None:
        Kmax = 2*np.max(np.abs(samples_locations), axis=0)
        samples_locations /= Kmax
```

If this is the only change you mean, I can get a quick PR and we could close this issue.

**Comment by zaccharieramzi** [comment]
I made a PR for this (#37 )
