### ISSUE TITLE
Add python 3.8 to travis and maybe remove python 3.5

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap-mri#100]
Currently, the travis tests are done in python 3.5, 3.6 and 3.7

However, scikit-learn has progressed to work on python 3.6 and above.
With this we have issues with travis testing in python 3.5:

```
 RuntimeError: Scikit-learn requires Python 3.6 or later. The current Python version is 3.5.6 installed in /home/travis/miniconda/envs/testenv/bin/python.
2065
```

**Comment by chaithyagr** [comment]
We have added `python 3.8` already. So all we need to decide is if we should remove python 3.5? 
In my opinion this reduces the amount of testing needed.

**Comment by philouc** [comment]
Yes please remove python3.5

**Comment by chaithyagr** [comment]
This is done..
