### ISSUE TITLE
'mr_transform' is not executable

### ISSUE THREAD

**Issue by guanhuaw** [CEA-COSMIC/pysap-mri#106]
When running the non-cartesian recon example and test_binding.py, both reported 'mr_transform' is not found. And all the files under build/temp/export/bin are not executable, though the building log reported no error or warning.

**Comment by chaithyagr** [comment]
Hello @guanhuaw , thank you for using the package and reporting the issue you see.

What is your OS and can you see the binaries in `build/temp/extern/bin` ? 

Below, I have replied some concerns assuming you have a linux machine (preferably Ubuntu)

If you see the binaries, try to see if running them works, if it fails, try to use `chmod +x *` , which should make them executable.

Once you are able to execute, can you please copy over these files to `/usr/bin` or `/usr/local/bin` . This will ensure this issue does not come up in future. Another option is to add this path to your PATH variable, although this isnt exactly a permanent solution.

Finally, a quick way to see all the features of the package can be done through https://github.com/CEA-COSMIC/pysap-tutorials on jupyter notebook.

**Comment by guanhuaw** [comment]
Thanks much! Yes, it is running an ubuntu machine. After giving the execution rights, the binaries under build/temp/extern/bin are now executable and test_binding.py runs successfully.
