### ISSUE TITLE
Include FISTA restart in pysap-mri

### ISSUE THREAD

**Issue by zaccharieramzi** [CEA-COSMIC/pysap-mri#12]
Since the restarting versions of FISTA have been included in `modopt`, we could allow the user to use them in [`sparse_rec_fista`](https://github.com/CEA-COSMIC/pysap-mri/blob/master/mri/numerics/reconstruct.py#L36) in `pysap-mri`.

**Comment by chaithyagr** [comment]
I am assuming this can be closed as fixes at TOT
Please reopen if I am wrong, @zaccharieramzi
