### ISSUE TITLE
[TASK][Plugin Merge] Merging `pysap-mri-online` to `pysap-mri`

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap-mri#129]
This issue tracks the merging of `pysap-mri-online` plugin developed by @paquiteau at [here](https://github.com/paquiteau/pysap-mri-online)
Steps to be done:

- [x] Generators: Return single trajectory of kspace data per iteration. 
    - [x] Can it be batched?
   ~~- Non-Cartesian?~~
- [X] Operators: 
    - [X] Inherit from base classes in `pysap-mri`
    - Dont need prox op as it exists in `modopt`
- [ ] Tests:
    - [X] Have tests in place for operators,
    - [ ] integration test for complete reconstruction.
- [x] Optimizers:
    - [x] Basic gradient descent and acceleration operators: Move to Modopt! Have a chat with @sfarrens about [codes(https://github.com/paquiteau/pysap-mri-online/blob/master/online/optimizers/gradescent.py)
    - [x] For algorithms call, try to reduce redundancy and have the same function which creates online version of the algorithm.
         - [x] A lot of refactoring needed, @paquiteau to update on when can it be done (open a new issue if needed).
- [ ] Reconstructors:
    - [ ] Based on above refactoring, this must be added.

**Comment by paquiteau** [comment]
I don't plan on adding Non Cartesian Generator for now, It will probably requires some heavy changes in NonCartesianFFT/gpuNUFFT operators (update samples points and density compensation for instance), also, some extra algorithmic thinking (like the one of ColumnFFT) needs to be found to make it worth.

**Comment by paquiteau** [comment]
The ModOpt Integration of optimizer is tracked here: https://github.com/CEA-COSMIC/ModOpt/issues/194

**Comment by chaithyagr** [comment]
@paquiteau can we close this?

**Comment by paquiteau** [comment]
Yes ! All PR have been merged in their corresponding repos.
