### ISSUE TITLE
Issue during install

### ISSUE THREAD

**Issue by gavinlive** [CEA-COSMIC/pysap-mri#139]
During installation, the follow error appeared:

```
WARNING: Error parsing requirements for numpy: [Errno 2] No such file or directory: '<workspace_path>/bin/anaconda3/envs/<environment_name>/lib/python3.8/site-packages/numpy-1.19.2.dist-info/METADATA'
Installing collected packages: python-utils, numpy, threadpoolctl, pyerfa, progressbar2, joblib, scikit-learn, pyqtgraph, modopt, astropy, python-pysap
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Can't uninstall 'numpy'. No files were found to uninstall.
```

where I've substituted <workspace_path> and <environment_name>. Seems like the pysap-mri tries to build a new version of numpy?

**Comment by chaithyagr** [comment]
Do you still face this issue?  Can you please try this on a new environment. I feel this isnt an issue with pysap-mri particularly but rather some specific issue where the files downloaded for numpy install werent found.

**Comment by chaithyagr** [comment]
Closing here due to lack of more details. Based on the CI we find it to be working fine. @gavinlive please do reopen if case you find this issue repeating.
