### ISSUE TITLE
Weights of the `prox_op` operator should not be set by the `sparse_rec*`

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/pysap-mri#19]
In `mri/numerics/reconstruct.py` the weights are set by the `sparse_rec*`, this is perfectly fine for basic norms such as the `ell_1` norm. However, for more sophisticated norm such as OSCAR norm, the weights are a little bit more complicated, hence they should be set by the proximity operator at the instanciation and not by the `sparse_rec*` functions

**Comment by zaccharieramzi** [comment]
Totally agree.

I think the best place for the weights to be set is in [`generate_operators`](https://github.com/CEA-COSMIC/pysap-mri/blob/master/mri/reconstruct/utils.py#L108).
