### ISSUE TITLE
Adding examples

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/pysap-mri#35]
Could we add examples to the MRI plugins this would be much easier to test and integrate the new features developed? 
Also, exemples could be tested with [CircleC](https://ci.appveyor.com/login)I to make sure that they are still running perfectly when we do changes?

**Comment by chaithyagr** [comment]
> Also, exemples could be tested with CircleCI to make sure that they are still running perfectly when we do changes?

How do we plan on doing this? I mean we can have examples run, but what will be the check criteria to ensure it is running right?

**Comment by chaithyagr** [comment]
Listing out Examples that we could have here, please add / remove on to the list:

{Cartesian / Non Cartesian} x {2D} x {Single Channel, Multichannel}
For Multichannel: {Self Calibrating and Calibrationless}
**Number = 6**

{Non Cartesian} x {3D} x {Single Channel, Multichannel}
For Multichannel: {Self Calibrating and Calibrationless}
**Number = 3**

{2D/3D} x Dictionary Learning.
**Number = 2**

**TOTAL = 11**

**Comment by chaithyagr** [comment]
As a first step, I will get a PR for following examples:
1) 2D Single Channel Cartesian with:
   * Linear Operator: PyWt Decimated Wavelet (Orthogonal, or Bi-Orthogonal Wavelet)
   * Optimization: With POGM, Condat-Vu, and Greedy FISTA

2) 2D Single Channel Non-Cartesian with:
   * Linear Operator: ISAP Undecimated Wavelet (Implement with rotated filters if necessary)
   * Optimization: same as above.


@LElgueddari , do you want to add or modify any?

**Comment by zaccharieramzi** [comment]
I think one optimisation algorithm should be enough for the purpose of the paper. If we want to showcase the possibilities to gain speed using different algorithms we can just refer to my benchmark.

**Comment by chaithyagr** [comment]
I think we have satisfied the purpose of this issue.
Re-purposing now to ensure we have one example for each type of reconstruction.

**Comment by chaithyagr** [comment]
I think this can be closed now as we have one example of each kind.
Closing.
