### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/pysap-mri#36]
Could we refactor the code just to have more explicit module names? 
For example, `reconstruct` module does not mean anything since the goal of the plugins is to do reconstruction.
An idea would be to split the modules according to their function i.e. `gradients`, `linear_operator` etc..

**Comment by chaithyagr** [comment]
I will get an updated code structure and update here before we make any changes.
We should ideally get at this after the #35 issue is fixed so that we have something to check the stability.

**Comment by chaithyagr** [comment]
@LElgueddari  and @chaithyagr  had a discussion on this and here is the set proposal that we have in mind.
@LElgueddari can you please give a thumbs up if you feel I havent missed out anything, or just point to out here.
@zaccharieramzi can you please review this and ensure we have not missed out on anything?

- mri
    - operators
        - _linear
             - dictionary
             - wavelet
        - _fourier
             - stack
             - cartesian
             - non-cartesian
                 - cpu / cuda / opencl
        - _gradient
        - _proximity

   - reconstructors
        - _base_reconstructor
            - self calibrating
                - L1 ESPIRIT based estimation
                - kspace center based estimation 
            - calibrationless (base class with common stuff, all below are individual classes as each have different parameters)
                - group LASSO
                - OWL
                - K-support Norm
                - Low Rank
                - etc..
            - single channel reconstructor

   - optimization
       - FISTA
       - CondatVu
       - POGM

   - utils
       - plotting : Holds basic 3D and 2D plotting function, to reduce dependence on pysap whose import takes too long.



We will have utils in each folder based on where it belongs to. 
Examples will remain same, we plan to add unit tests to respective folders than maintain it in a common folder. pytest will still find all the tests and run them right.


Going forward, we would want the base classes for _linear and _fourier to be moved into a different location given that many other plugins would use it.

**Comment by chaithyagr** [comment]
Logistics:
We plan to freeze any PRs while we are going through the process of refactoring to ensure we dont have pile up of new codes to refactor. This PR be primarily done by me and @LElgueddari (assigned).
We will have our own branch where we start on this task and have a common PR opened.

**Comment by zaccharieramzi** [comment]
What is the base_reconstructor? 
What will the optimization folder hold exactly? (The algorithms themselves are in Modopt)

**Comment by chaithyagr** [comment]
_base_reconstructor holds the base class which has all the common details for reconstruction, like dimension, number of channels etc. actual reconstructors derive from this class.

**Comment by chaithyagr** [comment]
All are merged, closing
