### ISSUE TITLE
Add tests for POGM optimizer

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap-mri#42]
This issue tracks writing 2 tests for POGM: Cartesian and Non-Cartesian cases. 

We will have linear operators with mu=0, and ensure that we have converged to adjoint of fourier operator

**Comment by chaithyagr** [comment]
I have a PR ready for this in https://github.com/chaithyagr/pysap-mri/tree/pogm_test
However, we will have to wait for #41 to hit to mainline to get this in.

**Comment by LElgueddari** [comment]
Any updates on this PR?
