### ISSUE TITLE
correct typo for clearer code

### ISSUE THREAD

**Issue by mathrip** [CEA-COSMIC/pysap-mri#61]
In _non_cartesian.py_ change 
**num_slice** by  **num_stack** 
**acq_num_slice** by **acq_num_stack**
refract to all the code

**Comment by zaccharieramzi** [comment]
I don't think we want these kinds of changes. Let's do it progressively as we change the code naturally. Otherwise, the code history will be a bit messed up.

**Comment by chaithyagr** [comment]
I agree, in my opinion, this is a small change that can happen gradually and we don't need an issue for this. 
 Lets close this?

**Comment by mathrip** [comment]
Ok I'm going to close the issue
