### ISSUE TITLE
Better sparsity promotion

### ISSUE THREAD

**Issue by zaccharieramzi** [CEA-COSMIC/pysap-mri#66]
Right now sparsity is promoted by an L1 Norm on all the wavelet coefficients in the examoles. However the coarse scale of the wavelet transform has no reason to be sparse and shouldn't be biased.

The examples should highlight that. For this, it might be necessary to have a helper function which for a given `mu` and a given wavelet transform returns the corresponding thresholding levels for all coefficients (the ones corresponding to the coarse scale being 0)

**Comment by chaithyagr** [comment]
@zaccharieramzi, given that all proximity opertaors lie in Modopt (General ones), wouldnt this helper function be best suited to sit in Modopt? 
That way even other modalities can make use of such a regularizer in my opinion.

**Comment by philouc** [comment]
@zaccharieramzi You're absolutely right! This should be done quickly. 
@chaithyagr either in ModOpt or in PySAP core?

**Comment by zaccharieramzi** [comment]
No but the regularizers (modopt) and the transforms (pysap) already support such a way. It just needs to be used properly in pysap-mri.

Or maybe you meant the helper function in which case probably pysap is more suited since it has to do with which coefficients are the coarse ones. Maybe @sfarrens already has a helper function for this btw?

But anyway this can be done without the helper function on a case by case basis if we want to have something quickly.

**Comment by chaithyagr** [comment]
Adding this to the coding sprint as it is more common and needs some minute change across pysap core or modopt as well.

**Comment by chaithyagr** [comment]
@zaccharieramzi and @sfarrens can we discuss this in the sprint? I feel we could come to a common grounf before getting anywhere with this.
