### ISSUE TITLE
Fixed variable name for consistency

### ISSUE THREAD

**Issue by mathrip** [CEA-COSMIC/pysap-mri#72]
Need to ensure that all the variables in the fourier operator have the same name.  It create conflicts when self_calibrating is calling 'samples' whether 'samples' doesn't exist in Stack3DNFFT.
For now we had  ' self.samples = kspace_loc' in Stack3DNFFT to fix the situation

**Comment by chaithyagr** [comment]
We need a general change of variable here. It is better to call kspace_loc as location of kspace for all the Fourier operators. We seem to have missed this bug due to no tests for reconstruction with Stacked3DFFT.

**Comment by chaithyagr** [comment]
Getting at this now on priority as it affects those who use StackFFT
