### ISSUE TITLE
Undefined variable when extracting sensivity maps

### ISSUE THREAD

**Issue by Daval-G** [CEA-COSMIC/pysap-mri#75]
I was trying to run the example "SelfCalibrationReconstruction_Cartesian.py" but changed the Fourier operator (and the data accordingly) to a Stacked3DNFFT to test it.

The reconstructor raised an error because the variable `z_sample_loc` was not defined in: https://github.com/CEA-COSMIC/pysap-mri/blob/c39764bf07c8dbefdb60c4e0be92fa3f96b477e2/mri/reconstructors/utils/extract_sensitivity_maps.py#L166

It may be related to a previous issue: https://github.com/CEA-COSMIC/pysap-mri/issues/62

**Comment by chaithyagr** [comment]
This seems to be an atifact of moving to new functions for accomodating variable kspace z lines in #58 
I will get a PR for fixing this and #72 . 
Also, I will add tests to ensure we dont miss this in future thereby increasing coverage also

**Comment by chaithyagr** [comment]
Fixed with #76
