### ISSUE TITLE
Fix `generate_operator` based on new function descriptions 

### ISSUE THREAD

**Issue by Martin11847** [CEA-COSMIC/pysap-mri#8]
`generate_operator` from `pysap.numerics.utils` doesn't work for 3D reconstruction, it would be helpful to link them with the one existing in `pysap.plugins.mri.reconstruct_3D`

**Comment by chaithyagr** [comment]
I will repurpose this as a bug to track obtaining all operators such that it works well with the updated codebase. For now, there is some issues with this, with some changes in function descriptions. 
I will get a PR for this hopefully sometime tomorrow. 
I will ensure it works for 3D also as required.

**Comment by chaithyagr** [comment]
I think we can close this as it is addressed while we added 3D examples. @LElgueddari can you please close it, if you feel the same?

**Comment by LElgueddari** [comment]
This will be fixed in PR #51

**Comment by chaithyagr** [comment]
Fixed in #51
