### ISSUE TITLE
[Enhancement] Fix Generic Cost to actually account for Proximities from variable splitting methods

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap-mri#80]
**Describe the bug**
Currently the linear composition operator carries out linear operation and adjoint operation, this must not be done as all the algorithms generally carry out the proximity on the wavelet domain coefficients directly.

https://github.com/CEA-COSMIC/ModOpt/blob/609ecded944b6bfd746106c917d6043219701fa4/modopt/opt/proximity.py#L319-L321

The fix is minor, we just need to remove these extra operations.

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

**UPDATED**

Based on discussion, we plan to fix the Generic Cost Operator here so that it can accept x_new and y_new and calculate cost right in analysis formulation

**Comment by zaccharieramzi** [comment]
Wait, we should first have @sfarrens on this because I want to understand the origin of this design first.

**Comment by chaithyagr** [comment]
> Wait, we should first have @sfarrens on this because I want to understand the origin of this design first.



Oops... My bad, didnt get this update. I dont want to flip flop now, lets see what @sfarrens has to say, I will not work on this PR for now..

**Comment by sfarrens** [comment]
Hi @chaithyagr and @zaccharieramzi,

I am not sure I got what the exact question was, but I can try at least to explain the reason for how ModOpt handles proximity operators. 

For any given proximity operator the `op` method is intended to perform the operation required by "prox" in a given optimisation algorithm. *e.g.* for `SparseThreshold` this returns by default the soft thresholding of whatever is passed to prox() by the algorithm. I think this is pretty clear and is of course the primary purpose of these operators.

This `cost` method on the other hand aims to return the contribution this type of regularisation (*e.g.* l_1, l_2, *etc.*) to the overall cost function. This is a little bit less obvious, but the idea was that for a given algorithm, by simply changing the proximity operator, you should automatically get the corresponding cost without having to change anything else. The issue with this is that if the regularisation depends on the linear operator(s) used then this needs to be passed to the proximity operator when the object is defined. It is possible that this framework does not easily extend to all use cases, in which case we can discuss alternatives to handing the cost calculation.

**Comment by chaithyagr** [comment]
Well I think @zaccharieramzi 's point is that (please correct me if I am wrong) we could have the proximities just to handle what they intend to do, ie the proximity and cost (with no idea of the linear operator). It could be up to the algorithm to call the cost and proximities right. 
In my opinion, we are duplicating code by providing `linear_op` to both the algorithm and the `prox_op`.
In our case here, I need to fix the generic_cost to handle the costs differently for analysis formulation.

**Comment by zaccharieramzi** [comment]
I agree with what @chaithyagr has just said.

**Comment by sfarrens** [comment]
OK, sounds good to me.

**Comment by chaithyagr** [comment]
@zaccharieramzi can we say that this is now tackled and close this? 
Is there any other opens?

**Comment by zaccharieramzi** [comment]
Well except the fact we still have this `args` thing yes I think it's ok

**Comment by chaithyagr** [comment]
Closing.
